# Generated by Django 4.1.1 on 2022-09-26 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestbasicsApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='roomNumber',
            new_name='userId',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='timeStamp',
        ),
        migrations.AddField(
            model_name='hotel',
            name='timeSttimeamp',
            field=models.DateTimeField(null=True),
        ),
    ]
