# Generated by Django 4.1.1 on 2022-09-26 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestbasicsApp', '0002_rename_roomnumber_hotel_userid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='timeSttimeamp',
            new_name='time',
        ),
    ]
