# Generated by Django 4.1.1 on 2022-09-26 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestbasicsApp', '0003_rename_timesttimeamp_hotel_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='id',
        ),
        migrations.AlterField(
            model_name='hotel',
            name='userId',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
