# Generated by Django 4.1.1 on 2022-10-09 07:10

import RestbasicsApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestbasicsApp', '0004_remove_hotel_id_alter_hotel_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Make_ID', models.IntegerField()),
                ('Make_Name', models.CharField(max_length=100)),
                ('Model_ID', models.IntegerField()),
                ('Model_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Count', models.IntegerField()),
                ('Message', models.CharField(max_length=200)),
                ('SearchCriteria', models.CharField(max_length=200)),
                ('Results', models.Field(verbose_name=RestbasicsApp.models.CarModel)),
            ],
        ),
        migrations.DeleteModel(
            name='hotel',
        ),
    ]
