# Generated by Django 4.1.1 on 2022-10-09 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestbasicsApp', '0006_rename_make_id_carmodel_makeid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmodel',
            old_name='MakeID',
            new_name='Make_ID',
        ),
        migrations.RenameField(
            model_name='carmodel',
            old_name='MakeName',
            new_name='Make_Name',
        ),
        migrations.RenameField(
            model_name='carmodel',
            old_name='ModelID',
            new_name='Model_ID',
        ),
        migrations.RenameField(
            model_name='carmodel',
            old_name='ModelName',
            new_name='Model_Name',
        ),
    ]
